=== MarcoFlo/AssignmentDP2/Solution/ass1/xsd/accounts.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 

 <xsd:element name="bankInfo">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="account" type="AccountType" minOccurs="0" maxOccurs="unbounded">
      <xsd:unique name="yearUniqueness">
        <xsd:selector xpath="yearOperations"/>
        <xsd:field xpath="@year"/>
      </xsd:unique>
      <xsd:unique name="holderUniqueness">
        <xsd:selector xpath="holder"/>
        <xsd:field xpath="."/>
      </xsd:unique>
    </xsd:element>
    <xsd:element name="holder" type="HolderType" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
  </xsd:complexType>
  <xsd:unique name="accountIDUniqueness">
  	<xsd:selector xpath="account"/>
  	<xsd:field xpath="@number"/>
  </xsd:unique>
  <xsd:key name="holderIDKey">
  	<xsd:selector xpath="holder"/>
  	<xsd:field xpath="@fiscalID"/>
  </xsd:key>
  <xsd:keyref name="holderReference" refer="holderIDKey">
  	<xsd:selector xpath="account/holder"/>
  	<xsd:field xpath="."/>
  </xsd:keyref>
 </xsd:element>

 <xsd:complexType name="AccountType">
  <xsd:sequence> 
   <xsd:element name="holder" type="FiscalIDType" minOccurs="1" maxOccurs="unbounded"/> 
   <xsd:element name="yearOperations" type="YearOperationsType" minOccurs="0" maxOccurs="unbounded"/> 
  </xsd:sequence> 
  <xsd:attribute name="number" type="xsd:positiveInteger" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="HolderType">
  <xsd:attribute name="name" type="xsd:string" use="required"/>
  <xsd:attribute name="address" type="xsd:string" use="required"/>
  <xsd:attribute name="fiscalID" type="FiscalIDType" use="required"/>
 </xsd:complexType>

 <xsd:complexType name="YearOperationsType">
  <xsd:sequence> 
   <xsd:element name="operation" type="OperationType" minOccurs="1" maxOccurs="unbounded"/> 
  </xsd:sequence> 
  <xsd:attribute name="year" type="xsd:positiveInteger" use="required"/>
 </xsd:complexType>
 
 <xsd:simpleType name="Currency">
  <xsd:restriction base="xsd:decimal"> 
   <xsd:fractionDigits value="2"/> 
  </xsd:restriction> 
 </xsd:simpleType>

 <xsd:complexType name="OperationType">
  <xsd:all>
    <xsd:element name="description" type="xsd:string" minOccurs="0"/>
  </xsd:all>
  <xsd:attribute name="date" type="xsd:date" use="required"/>
  <xsd:attribute name="amount" type="Currency" use="required"/>
 </xsd:complexType>
 
 <xsd:simpleType name="FiscalIDType">
  <xsd:restriction base="xsd:string">
   <xsd:pattern value="[A-Za-z0-9]{16}"/>
  </xsd:restriction>
 </xsd:simpleType>
</xsd:schema>

=== MarcoFlo/AssignmentDP2/Solution/ass1/xsd/accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<bankInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="accounts.xsd">
	<account
	    xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
	    xsd:noNamespaceSchemaLocation="account.xsd" number="123456">
	    <holder>ABCDEF00A00Y000B</holder>
	    <holder>ABCDEF00A00Y000C</holder>
	    <yearOperations year="2019">
	     <operation date="2019-06-01" amount="1000.00">
	       <description>Salary</description>
	     </operation>
	     <operation date="2019-10-01" amount="-400.00">
	       <description>Credit card operation</description>
	     </operation>
	    </yearOperations>
	</account>
	<account
	    xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
	    xsd:noNamespaceSchemaLocation="account.xsd" number="6543">
	    <holder>ABCDEF00A00Y000B</holder>
	</account>
	<holder name="Elia" address="Via dei Pioppi, 20" fiscalID="ABCDEF00A00Y000B"/>
	<holder name="Elia Jr" address="Via dei Pioppi, 20" fiscalID="ABCDEF00A00Y000C"/>
	<holder name="Elis" address="Via degli Ontani, 20" fiscalID="ABCDEF00A00Y000D"/>
</bankInfo>
