=== MarcoFlo/AssignmentDP2/Solution/ass1/xsd/biblio_3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://pad.polito.it/dp2/biblio"
	    xmlns:tns="http://pad.polito.it/dp2/biblio"
>
  
    <element name="biblio" type="tns:BiblioType">
		<key name="journalKey">
			<selector xpath="journals/journal" />
			<field xpath="@ISSN" />
		</key>
		<keyref name="journalRef" refer="tns:journalKey">
			<selector xpath="items/article" />
			<field xpath="@journal" />
		</keyref>
		<key name="issueKey">
			<selector xpath="journals/journal/issue" />
			<field xpath="@id"/>
		</key>
		<keyref name="issueRef" refer="tns:issueKey">
			<selector xpath="items/article" />
			<field xpath="@issue" />
		</keyref>
		<key name="itemKey">
			<selector xpath="items/*"/>
			<field xpath="@id"/>
		</key>
		<keyref name="itemRef" refer="tns:itemKey">
			<selector xpath="items/*/citedBy" />
			<field xpath="." />
		</keyref>
		<key name="bookKey">
			<selector xpath="items/book" />
			<field xpath="@ISBN" />
		</key>
		<unique name="journalTitleUniqueness">
			<selector xpath="journals/journal" />
			<field xpath="title" />
		</unique>
		<keyref name="bookRef" refer="tns:bookKey">
			<selector xpath="items/chapter" />
			<field xpath="@book" />
		</keyref>
		<unique name="chapterNumberUniqueness">
			<selector xpath="items/chapter" />
			<field xpath="@book" />
			<field xpath="@number" />
		</unique>
		<unique name="chapterTitleUniqueness">
			<selector xpath="items/chapter" />
			<field xpath="@book" />
			<field xpath="title" />
		</unique>
	</element>
	
	<complexType name="BiblioType">
		<sequence>
			<element name="items" type="tns:BiblioItemsType"/>
			<element name="journals" type="tns:BiblioJournalsType"/>
		</sequence>
	</complexType>
	

	<complexType name="BiblioItemsType">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="article" type="tns:ArticleType"/>
			<element name="book" type="tns:BookType"/>
			<element name="chapter" type="tns:ChapterType"/>
		</choice>
	</complexType>
	
	<complexType name="BiblioJournalsType">
		<sequence>
			<element name="journal" type="tns:JournalType" maxOccurs="unbounded" minOccurs="0">
				<unique name="issueUniqueness">
					<selector xpath="issue" />
					<field xpath="@year" />
					<field xpath="@number" />
				</unique>	
			</element>
		</sequence>
	</complexType>
	
	<complexType name="ItemType">
		<sequence>
			<element name="author" type="string" maxOccurs="unbounded" minOccurs="1"/>
			<element name="title" type="string"/>
			<element name="subtitle" type="string" minOccurs="0"/>
			<element name="citedBy" type="integer" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="integer"/>
	</complexType>
	
	<complexType name="ArticleType">
		<complexContent>
			<extension base="tns:ItemType">
				<attribute name="journal" type="tns:ISSNCode" use="required"/>
				<attribute name="issue" type="integer" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="BookType">
		<complexContent>
			<extension base="tns:ItemType">
				<sequence>
					<element name="publisher" type="string"></element>
				</sequence>
				<attribute name="ISBN" type="tns:ISBNCode" use="required"/>
				<attribute name="year" type="gYear" use="required"/>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ChapterType">
		<complexContent>
			<extension base="tns:ItemType">
				<attribute name="book" type="tns:ISBNCode" use="required"/>
				<attribute name="number" type="positiveInteger" use="required"/>
			</extension>
		</complexContent>
	</complexType>
		
	<complexType name="JournalType">
		<sequence>
			<element name="title" type="string"></element>
			<element name="publisher" type="string"></element>
			<element name="issue" maxOccurs="unbounded" minOccurs="0">
				<complexType>
					<attribute name="id" type="integer" use="required"/>
					<attribute name="year" type="gYear" use="required"/>
					<attribute name="number" type="positiveInteger" use="required"/>					
				</complexType>
			</element>
		</sequence>
		<attribute name="ISSN" type="tns:ISSNCode" use="required"/>
	</complexType>
		
	<!-- ISBN code is a 10 or 13 digit code. If it is 10 digits long the last digit may be a X -->  
	<simpleType name="ISBNCode"> 
	  <restriction base="string"> 
	   <pattern value="[0-9]{13}"/>
	   <pattern value="[0-9]{9}([0-9]|X)"/>
	  </restriction> 
	</simpleType>
	
	<!-- ISSN code is a 8 digit code with a dash dividing the two groups
	     of 4 digits and the last digit may be a X -->  
	<simpleType name="ISSNCode"> 
	  <restriction base="string"> 
	   <pattern value="[0-9]{4}-[0-9]{3}([0-9]|X)"/>
	  </restriction> 
	</simpleType>
</schema>

=== MarcoFlo/AssignmentDP2/Solution/ass1/xsd/biblio_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:biblio xmlns:tns="http://pad.polito.it/dp2/biblio" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pad.polito.it/dp2/biblio biblio_3.xsd ">
  <items>
    <article id="0" issue="7" journal="1551-3203">
    	<author>M. Cheminod</author>
    	<author>A. Pironti</author>
    	<author>R. Sisto</author>
    	<title>Formal Vulnerability Analysis of a Security System for Remote Fieldbus Access</title>
    </article>
    <book id="1" ISBN="0131411551" year="2004">
		<author>W. Richard Stevens</author>
    	<author>Bill Fenner</author>
    	<author>Andrew M. Rudoff</author>
    	<title>Unix network programming</title>
    	<subtitle>Volume 1: The sockets networking API</subtitle>
    	<publisher>Addison Wesley</publisher>
    </book>
    <article id="2" issue="1" journal="0141-9331">
        <author>T. Sauter</author>
	    <author>C. Schwaiger</author>
	    <title>Achievement of secure Internet access to fieldbus systems</title>
    	<citedBy>0</citedBy>
    </article>
    <chapter id="3" book="0131411551" number="1">
    	<author>W. Richard Stevens</author>
    	<author>Bill Fenner</author>
    	<author>Andrew M. Rudoff</author>
    	<title>Introduction</title>
    </chapter>
    <chapter id="4" book="0131411551" number="2">
    	<author>W. Richard Stevens</author>
    	<author>Bill Fenner</author>
    	<author>Andrew M. Rudoff</author>
    	<title>The Transport Layer: TCP, UDP and SCTP</title>
    </chapter>
    <book id="5" ISBN="9781449358068" year="2013">
		<author>Leonard Richardson</author>
    	<author>Mike Amundsen</author>
    	<title>RESTful Web APIs</title>
    	<publisher>Oâ€™Reilly</publisher>
    </book>
    <chapter id="6" book="9781449358068" number="1">
		<author>Leonard Richardson</author>
    	<author>Mike Amundsen</author>
    	<title>Surfing the Web</title>
    </chapter>
  </items>
  <journals>
    <journal ISSN="1551-3203">
	    <title>IEEE Transactions on Industrial Informatics</title>
	    <publisher>IEEE</publisher>
	    <issue id="1" number="1" year="2011"/>
	    <issue id="2" number="2" year="2011"/>
	    <issue id="3" number="3" year="2011"/>
	    <issue id="4" number="4" year="2011"/>
	    <issue id="5" number="5" year="2011"/>
	    <issue id="6" number="6" year="2011"/>
	    <issue id="7" number="7" year="2011"/>
	    <issue id="8" number="8" year="2011"/>
	    <issue id="9" number="9" year="2011"/>
	    <issue id="10" number="10" year="2011"/>
	    <issue id="11" number="11" year="2011"/>
	    <issue id="12" number="12" year="2011"/>
    </journal>
    <journal ISSN="0141-9331">
  		<title>Microprocessors and Microsystems</title>
  		<publisher>Elsevier</publisher>
    	<issue id="0" number="7" year="2002"/>
  	</journal>
  </journals>
</tns:biblio>

=== MarcoFlo/AssignmentDP2/Assignment1/xsd/biblio_3.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:biblio xmlns:ns2="http://pad.polito.it/dp2/biblio_3"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://pad.polito.it/dp2/biblio_3 biblio_3.xsd">
    <article journal="0141-9331" issue="0" id="0">
        <author>T. Sauter</author>
        <author>C. Schwaiger</author>
        <title>Achievement of secure Internet access to fieldbus systems</title>
        <citedBy>14</citedBy>
    </article>
    <article journal="1551-3203" issue="7" id="1">
        <author>M. Cheminod</author>
        <author>A. Pironti</author>
        <author>R. Sisto</author>
        <title>Formal Vulnerability Analysis of a Security System for Remote Fieldbus Access</title>
        <citedBy>4</citedBy>
    </article>
    <book ISBN="0131411551" year="2004" id="2">
        <author>W. Richard Stevens</author>
        <author>Bill Fenner</author>
        <author>Andrew M. Rudoff</author>
        <title>Unix network programming</title>
        <subtitle>Volume 1: The sockets networking API</subtitle>
        <citedBy>0</citedBy>
        <publisher>Addison Wesley</publisher>
        <chapter number="0" id="4">
            <author>AAAA</author>
            <title>AAAA</title>
            <citedBy>7</citedBy>
        </chapter>
        <chapter number="1" id="7">
            <author>BBBB</author>
            <title>BBBB</title>
            <citedBy>14</citedBy>
        </chapter>
    </book>
    <book ISBN="0131411951" year="2004" id="3">
        <author>Bill</author>
        <author>Andrew</author>
        <title>Unix network</title>
        <subtitle>Volume 1</subtitle>
        <publisher>Addison</publisher>
        <chapter number="0" id="8">
            <author>AAAA</author>
            <title>AAAA</title>
            <citedBy>14</citedBy>
        </chapter>
        <chapter number="1" id="14">
            <author>BBBB</author>
            <title>BBBB</title>
            <citedBy>7</citedBy>
        </chapter>
    </book>
    <journal ISSN="0141-9331">
        <title>Microprocessors and Microsystems</title>
        <publisher>Elsevier</publisher>
        <issue id="0" year="2002" number="7"/>
    </journal>
    <journal ISSN="1551-3203">
        <title>IEEE Transactions on Industrial Informatics</title>
        <publisher>IEEE</publisher>
        <issue id="1" year="2011" number="1"/>
        <issue id="2" year="2011" number="2"/>
        <issue id="3" year="2011" number="3"/>
        <issue id="4" year="2011" number="4"/>
        <issue id="5" year="2011" number="5"/>
        <issue id="6" year="2011" number="6"/>
        <issue id="7" year="2011" number="7"/>
        <issue id="8" year="2011" number="8"/>
        <issue id="9" year="2011" number="9"/>
        <issue id="10" year="2011" number="10"/>
        <issue id="11" year="2011" number="11"/>
        <issue id="12" year="2011" number="12"/>
    </journal>
    <journal ISSN="1551-3000">
        <title>IEEE Transactions</title>
        <publisher>IEEE</publisher>
        <issue id="13" year="2011" number="1"/>
        <issue id="14" year="2011" number="2"/>
        <issue id="15" year="2013" number="1"/>
    </journal>
</ns2:biblio>
