=== MarcoFlo/AssignmentDP2/Assignment1a/xsd/accounts.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="bank">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="accounts" type="AccountListType"/>
                <xsd:element name="holders" type="HolderListType"/>
            </xsd:sequence>
        </xsd:complexType>

<!--    guarantee the account number uniqueness-->
        <xsd:unique name="accountNumKey">
            <xsd:selector xpath="accounts/account"/>
            <xsd:field xpath="@number"/>
        </xsd:unique>

<!--    guarantee the fiscalCode uniqueness into the bank system-->
        <xsd:key name="cfKey">
            <xsd:selector xpath="holders/holder"/>
            <xsd:field xpath="@fiscalCode"/>
        </xsd:key>

<!--    guarantee that no holder with the same name have the same cf through out the document-->
        <xsd:keyref name="cfRef" refer="cfKey">
            <xsd:selector xpath="accounts/account/holder"/>
            <xsd:field xpath="."/>
        </xsd:keyref>
    </xsd:element>


    <xsd:complexType name="AccountListType">
        <xsd:sequence>
            <xsd:element name="account" type="AccountType" minOccurs="1" maxOccurs="unbounded">
                <xsd:unique name="cfHolderUnique">
                    <xsd:selector xpath="holder"/>
                    <xsd:field xpath="."/>
                </xsd:unique>
                <xsd:unique name="yearOperationsKey">
                    <xsd:selector xpath="yearOperations"/>
                    <xsd:field xpath="@year"/>
                </xsd:unique>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="HolderListType">
        <xsd:sequence>
            <xsd:element name="holder" type="HolderType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="AccountType">
        <xsd:sequence>
            <xsd:element name="holder" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="yearOperations" type="YearOperationsType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="number" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="HolderType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="fiscalCode" type="FiscalCodeType" use="required"/>
        <xsd:attribute name="address" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="HolderCFType">
        <xsd:attribute name="fiscalCode" type="FiscalCodeType" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="YearOperationsType">
        <xsd:sequence>
            <xsd:element name="operation" type="OperationType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="year" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="Currency">
        <xsd:restriction base="xsd:decimal">
            <xsd:fractionDigits value="2"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="OperationType">
        <xsd:all>
            <xsd:element name="description" type="xsd:string" minOccurs="0"/>
        </xsd:all>
        <xsd:attribute name="date" type="xsd:date" use="required"/>
        <xsd:attribute name="amount" type="Currency" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="FiscalCodeType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-zA-Z0-9]{16}"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== MarcoFlo/AssignmentDP2/Assignment1a/xsd/accounts.xml
<?xml version="1.0"?>
<bank
        xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
        xsd:noNamespaceSchemaLocation="accounts.xsd">
    <accounts>
        <account number="123456">
            <holder>abcdefghijklmno1</holder>
            <yearOperations year="2019">
                <operation date="2019-01-01" amount="12.1"/>
            </yearOperations>
        </account>
        <account number="1234567">
            <holder>abcdefghijklmno1</holder>
            <holder>abcdefghijklmno2</holder>
            <yearOperations year="2019">
                <operation date="2019-01-01" amount="12.1"/>
            </yearOperations>
            <yearOperations year="2020">
                <operation date="2020-01-01" amount="12.1"/>
            </yearOperations>
        </account>
        <account number="12345678">
            <holder>abcdefghijklmno2</holder>
            <yearOperations year="2019">
                <operation date="2019-05-01" amount="15.55"/>
            </yearOperations>
        </account>
    </accounts>
    <holders>
        <holder name="Elia" fiscalCode="abcdefghijklmno1" address="via torino, 50"/>
        <holder name="Sandro" fiscalCode="abcdefghijklmno2" address="via milano, 10"/>
    </holders>
</bank>
